# Generated by Django 2.0 on 2019-03-09 15:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimalist', '0003_product_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
