# Generated by Django 2.0 on 2019-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimalist', '0004_storagecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagecredentials',
            name='credentials',
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='auth_provider_x509_cert_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='auth_uri',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='client_email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='client_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='client_x509_cert_url',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='private_key',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='private_key_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='project_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='token_uri',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecredentials',
            name='type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
